services:
  offline_postgres_dyplom:
    container_name: offline_postgres_dyplom
    build:
      context: ./postgreSQL
      dockerfile: postgresDB.Dockerfile
      args:
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASS}
        DB_NAME: ${DB_NAME}
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgreSQL/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - offline_dyplom_network
  offline_pgadmin_dyplom:
    container_name: offline_pgadmin_dyplom
    build:
      context: ./postgreSQL
      dockerfile: pgAdmin.Dockerfile
      args:
        PGADMIN_EMAIL: ${PGADMIN_EMAIL}
        PGADMIN_PASSWORD: ${PGADMIN_PASSWORD}
    restart: unless-stopped
    depends_on:
      - offline_postgres_dyplom
    ports:
      - ${PGADMIN_PORT_EX}:${PGADMIN_PORT_NATIVE}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - offline_dyplom_network
  offline_frontend_dyplom:
    container_name: offline_frontend_dyplom
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
      args:
        PORT_REFERENCE: ${PORT_REFERENCE}
        HOST_REFERENCE: ${HOST_REFERENCE}
    restart: unless-stopped
    depends_on:
      - offline_backend_server_caddy_dyplom
    ports:
      - ${FRONTEND_PORT_EX}:${FRONTEND_PORT_NATIVE}
    volumes:
      - ./frontend:/app
      - node_modules_cache:/app/node_modules
    environment:
      VITE_BACKEND_URL_PREFIX: ${VITE_BACKEND_URL_PREFIX}
      VITE_WS_URL_PREFIX: ${VITE_WS_URL_PREFIX}
      VITE_WLED_URL_PREFIX: ${VITE_WLED_URL_PREFIX}
    networks:
      - offline_dyplom_network
  offline_php_dyplom:
    container_name: offline_php_dyplom
    build:
      context: ./backend
      dockerfile: php-manager.Dockerfile
      args:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
        POSTGRES_DB: ${DB_NAME}
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      TUYA_CLIENT_ID: ${TUYA_CLIENT_ID}
      TUYA_CLIENT_SECRET: ${TUYA_CLIENT_SECRET}
      TUYA_DEVICE_ID: ${TUYA_DEVICE_ID}
      TUYA_API_ENDPOINT: ${TUYA_API_ENDPOINT}
    restart: unless-stopped
    depends_on:
      - offline_postgres_dyplom
    volumes:
      - ./backend/php:/var/www/php
    networks:
      - offline_dyplom_network
  offline_backend_server_caddy_dyplom:
    container_name: offline_backend_server_caddy_dyplom
    build:
      context: ./backend
      dockerfile: caddy-server.Dockerfile
    restart: unless-stopped
    depends_on:
      - offline_php_dyplom
    ports:
      - ${BACKEND_CADDY_PORT_EX}:${BACKEND_CADDY_PORT_NATIVE}
    volumes:
      - ./backend/php:/var/www/php
    networks:
      - offline_dyplom_network
  offline_bun_api_dyplom:
    container_name: offline_bun_api_dyplom
    build:
      context: ./jsServer
      dockerfile: bun-api.Dockerfile
    restart: unless-stopped
    ports:
      - ${BUN_API_PORT_EX}:${BUN_API_PORT_NATIVE}
    volumes:
      - ./jsServer:/app
    networks:
      - offline_dyplom_network

volumes:
  postgres_data: null
  pgadmin_data: null
  node_modules_cache: null

networks:
  offline_dyplom_network:
    driver: bridge
