services:
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: reverse-proxy.Dockerfile
    container_name: main_reverse_proxy_inzynierka
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./reverse-proxy/Caddyfile:/etc/caddy/Caddyfile
      - ./reverse-proxy/data:/data
      - proxy_config:/config
      - ./reverse-proxy/certs:/certs
    networks:
      - inzynierka_network

  postgres:
    container_name: postgres_db_inzynierka
    build:
      context: ./postgreSQL
      dockerfile: postgresDB.Dockerfile
      args:
        DB_USER: ${POSTGRES_USER}
        DB_PASSWORD: ${POSTGRES_PASSWORD}
        DB_NAME: ${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgreSQL/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - inzynierka_network

  pgadmin:
    container_name: pgadmin_ui_inzynierka
    build:
      context: ./postgreSQL
      dockerfile: pgAdmin.Dockerfile
      args:
        PGADMIN_EMAIL: ${PGADMIN_EMAIL}
        PGADMIN_PASSWORD: ${PGADMIN_PASSWORD}
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - ${PGADMIN_PORT_EX}:${PGADMIN_PORT_NATIVE}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - inzynierka_network

  frontend:
    container_name: vue_frontend_inzynierka
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
      args:
        PORT_REFERENCE: ${PORT_REFERENCE}
        HOST_REFERENCE: ${HOST_REFERENCE}
    restart: unless-stopped
    depends_on:
      - backend-server-caddy
      - reverse-proxy
    volumes:
      - ./frontend:/app
      - node_modules_cache:/app/node_modules
    networks:
      - inzynierka_network

  php:
    container_name: php_manager_inzynierka
    build:
      context: ./backend
      dockerfile: php-manager.Dockerfile
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./backend/php:/var/www/php
    networks:
      - inzynierka_network

  backend-server-caddy:
    container_name: backend_server_caddy_inzynierka
    build:
      context: ./backend
      dockerfile: caddy-server.Dockerfile
    restart: unless-stopped
    depends_on:
      - php
      - reverse-proxy
    volumes:
      - ./backend/php:/var/www/php
    networks:
      - inzynierka_network

  cdn:
    container_name: caddy-cdn_inzynierka
    build:
      context: ./CDN
      dockerfile: caddy-cdn.Dockerfile
    restart: unless-stopped
    depends_on:
      - reverse-proxy
    volumes:
      - ./CDN/assets:/srv/assets:ro
    networks:
      - inzynierka_network

  bun-api:
    container_name: bun_api_inzynierka
    build:
      context: ./jsServer
      dockerfile: bun-api.Dockerfile
    restart: unless-stopped
    depends_on:
      - reverse-proxy
    volumes:
      - ./jsServer:/app
    networks:
      - inzynierka_network

volumes:
  postgres_data: null
  pgadmin_data: null
  node_modules_cache: null
  proxy_config: {}

networks:
  inzynierka_network:
    driver: bridge